### ISSUE TITLE
Recap team meeting + prepare iteration

### ISSUE THREAD

**Issue by simcard0000** [jazz-sim/crochet-craft#22]
**TO-DO**:

- [x] Share [FAQ document](https://docs.google.com/document/d/1TCyprXU-rYr2kSg67ugDkqI0j5cS0Cduyh8JzqIdcsI/edit) in the team's Discord server.
- [x] Share [LettuceMeet link](https://lettucemeet.com/l/3N5OP) for arranging team meeting in ~2 weeks.
- [x] Create tickets for the current iteration based on [meeting notes](https://docs.google.com/document/d/1dM5gv2YBLiiDVrhBj36Zwu0GwHsGvIql_3tlIzuEkRU/edit).
