### ISSUE TITLE
Clean up READMEs/documentation

### ISSUE THREAD

**Issue by simcard0000** [jazz-sim/crochet-craft#30]
**TO-DO**:
- Add the following badges:
    - [x] active development badge - example: ![active development](https://img.shields.io/badge/active%20dev-yes-brightgreen.svg)
    - [x] [GitHub code size in bytes](https://shields.io/badges/git-hub-code-size-in-bytes) - will only work if the repository is publicly accessible
    - [x] W3C Validation check - example: ![W3C Validation](https://img.shields.io/w3c-validation/default?targetUrl=https%3A%2F%2Fcrochetcraft.jtai.ca%2F&label=w3c%20check)
    - [x] Cloudflare Pages deployment - see: [cloudflare-pages-badges](https://github.com/aidenwallis/cloudflare-pages-badges), or use [GitHub tag checks state](https://shields.io/badges/git-hub-tag-checks-state) - will only work if the repository is publicly accessible
- [x]  `main > README` should describe file structure of overall repo....
- [x]  `main > DEVELOPMENT` should describe how to start up the web project...
- [x] Add [AccessLint](https://accesslint.com/) to `jazz-sim` org?
- [x] Add [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) to the `jazz-sim` org? - needs repos to be publicly accessible
- [x] Add workflow for automatically assigning labels + people to PRs.

**Comment by simcard0000** [comment]
@j-tai I moved this ticket from blocked to actionable and assigned both of us to it: 

>  `main > DEVELOPMENT` should describe how to start up the web project...

Was thinking of adding a Markdown file called `DEVELOPMENT` to the `main` branch at the top of the repo, perhaps you can add your documentation regarding set-up here?

**Comment by j-tai** [comment]
Un-assigning myself since @simcard0000 is better at these "repo infrastructure" tasks

**Comment by simcard0000** [comment]
Closing this as done because I'm finally putting up a PR for auto-assigning reviewers and labels lol
